import { readFile, writeFile } from "node:fs/promises";
const target=process.argv[2];
if(!target || !/^supabase\/migrations\/\d+_seed_game_awards_history\.sql$/.test(target)) throw Error("Pass a seed migration path generated by supabase migration new");
const proof=JSON.parse(await readFile('data/awards/verification/publication.json','utf8'));
const { createHash }=await import('node:crypto');
let sql="-- Verified TGA history, 2014–2025. Evidence: data/awards/verification/.\n-- Reviewed locally only; do not apply to production without separate authorization.\n-- Only awards tables are written. Library matches are computed by the import RPC.\nbegin;\n";
for(let year=2014;year<=2025;year++) {
  const event=JSON.parse(await readFile(`data/awards/tga-${year}.json`,"utf8"));
  if(event.gaps.length) throw Error(`${year}: unresolved extraction gaps`);
  const verified=proof.find(p=>p.year===year);
  if(event.status==='published'&&(!verified?.verified||verified.sha256!==createHash('sha256').update(JSON.stringify(event)).digest('hex')))throw Error(`${year}: data changed after verification`);
  const payload=JSON.stringify(event),delimiter=`$awards_${year}$`;
  if(payload.includes(delimiter)) throw Error("Dollar-quote collision");
  sql+=`select public.import_award_event(${delimiter}${payload}${delimiter}::jsonb);\n`;
}
await writeFile(target,sql+"commit;\n");console.log(`Generated ${target}`);
