import { readFile, writeFile } from 'node:fs/promises';
const report=JSON.parse(await readFile('data/awards/verification/report.json','utf8'));
const sources=JSON.parse(await readFile('data/awards/verification/sources.json','utf8'));
const clean=t=>String(t).replaceAll('|','\\|');
let md='# The Game Awards historical verification — 2026-10-08\n\nBranch: `feature/game-awards`. All twelve ceremony files and the unapplied seed are published and verified. No production database writes, deployment, or merge.\n\nNomination counts include winners and honorary recipient groups. “Matched” and “unresolved” count game-associated award entries, including performance credits; they are not unique-game counts. Unresolved library links are not missing historical results. Unowned and unlinked nominees remain visible by default; only the optional ownership filter hides them.\n\nFull nominee identities, winner flags, library IDs, ownership, source nominee labels, category evidence, and unresolved entries are in [the machine-readable report](../data/awards/verification/report.json). Source URLs and response fingerprints are in [sources.json](../data/awards/verification/sources.json). Reviewed changes are in [corrections.json](../data/awards/verification/corrections.json). Cached official rewind records were prioritized; contemporary specialist reporting supplied complete nominee lists and corrections to erroneous archive labels. Primary recipient statements and organizer videos supplemented honorary records.\n\n| Year | Status | Categories | Nominations | Winners | Matched | Unresolved | Non-game | Missing results |\n|---|---|---:|---:|---:|---:|---:|---:|---:|\n';
for(const y of report.years)md+=`| ${y.year} | ${y.status} | ${y.categories} | ${y.nominations} | ${y.winners} | ${y.matched} | ${y.unresolved} | ${y.non_game} | ${y.missing_data.length} |\n`;
for(const y of report.years){
 md+=`\n## ${y.year}\n\n${y.notes}\n\nMissing historical results: ${y.missing_data.length}.\n\n| Category | Nominations | Winner / honorary recipients | Matched | Unresolved | Nominee evidence |\n|---|---:|---|---:|---:|---|\n`;
 for(const c of y.category_details){const s=sources.find(s=>s.id===c.nominee_source);const evidence=s?`[${s.id}](${s.url})`:'Individual recipient records (see JSON)';md+=`| ${clean(c.name)} | ${c.nominations} | ${c.entries.filter(e=>e.status==='winner').map(e=>clean(e.nominee_name)).join('; ')} | ${c.matched} | ${c.unresolved} | ${evidence} |\n`;}
 md+='\nUnresolved game identities (unique titles; repeated category nominations remain separate in JSON):\n\n';
 md+=[...new Set(y.category_details.flatMap(c=>c.entries).filter(e=>['unresolved','ambiguous'].includes(e.match_status)).map(e=>e.game_title||e.nominee_name))].sort().map(t=>`- ${t}`).join('\n')+'\n';
}
md+='\n## The 16 ambiguous matches\n\nEvery entry was reviewed against its ceremony context and all existing exact-title candidates. The candidate groups have different canonical identities. No match was forced, no external ID was guessed, and no game was created. Release context alone cannot safely identify the library’s IGDB record. These remain eligible for a later evidence-backed manual link.\n\n| Year | Category | Nominee / associated game | Candidate library IDs (IGDB IDs) | Decision |\n|---|---|---|---|---|\n';
for(const a of report.ambiguous)md+=`| ${a.year} | ${a.category} | ${clean(a.title)} | ${a.candidates.map(g=>`${g.id} (${g.igdb_id})`).join(', ')} | Keep unlinked |\n`;
md+='\nDoom refers to the 2016 release, Prey to the 2017 release, the 2021 Resident Evil 4 VR winner to the Quest version, 2022/2023 Resident Evil 4 to the remake, 2023 Dead Space to the remake, and 2024 Silent Hill 2 to the remake. Distinct editions and VR modes are retained in award titles where nominated explicitly.\n\n## Application verification\n\nThe isolated PGlite database imports all 1,773 entries, matches 734 game-associated awards, retains all 2,348 inventory rows, and agrees with the JavaScript matcher. Publication through the authenticated route commits the event first and immediately expires awards, library, browsing, and Stats caches. A localhost browser test warms the staged caches, rejects the wrong database and an unverified year, publishes 2025 locally, and checks all four surfaces on the next request. Owned awards won increase from 146 to 163. See [publication test](awards-publication-report.json) and [responsive browser checks](awards-browser-fixture-report.json). These tests never use production Supabase.\n';
await writeFile('docs/game-awards-verification-2026-10-08.md',md);
console.log('Wrote per-year verification report');
