"use client";
import { useEffect, useState } from "react";
type Entry = { id: string; nominee_name: string; game_title: string | null; match_method: string | null; award_events: { year: number }; award_categories: { name: string } };
type Game = { id: number; title: string; platform: string | null; store: string | null };
function ReviewRow({ entry, onSaved }: { entry: Entry; onSaved: () => void }) {
  const [search, setSearch] = useState(""); const [games,setGames] = useState<Game[]>([]); const [selected,setSelected] = useState(""); const [busy,setBusy]=useState(false); const [error,setError]=useState("");
  useEffect(() => { const controller = new AbortController(); const timer = setTimeout(async () => {
    try { const response = await fetch(`/api/admin/awards?search=${encodeURIComponent(search)}`, { signal: controller.signal }); const data=await response.json(); if (!response.ok) throw Error(data.error); setGames(data.games); } catch(e) { if(!controller.signal.aborted) setError(e instanceof Error ? e.message : "Search failed"); }
  },300); return () => { clearTimeout(timer);controller.abort(); }; },[search]);
  async function save(gameId: number | null) { setBusy(true);setError(""); try { const response = await fetch("/api/admin/awards",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({entryId:entry.id,gameId})});const data=await response.json();if(!response.ok)throw Error(data.error);onSaved(); } catch(e) {setError(e instanceof Error ? e.message : "Save failed");} finally {setBusy(false);} }
  return <article className="rounded-xl border border-zinc-800 p-4"><h2 className="font-bold">{entry.nominee_name}</h2><p className="mt-1 text-xs text-zinc-500">{entry.award_categories.name} · {entry.award_events.year}{entry.game_title ? ` · ${entry.game_title}` : ""}{entry.match_method === "blocked" ? " · Rejected" : ""}</p><div className="mt-4 flex flex-wrap gap-2"><input aria-label={`Search library for ${entry.nominee_name}`} value={search} onChange={e=>{setSearch(e.target.value);setSelected("");}} placeholder="Search library title" className="rounded-lg border border-zinc-700 bg-zinc-950 p-2 text-sm"/><select aria-label={`Library match for ${entry.nominee_name}`} value={selected} onChange={e=>setSelected(e.target.value)} className="max-w-full rounded-lg border border-zinc-700 bg-zinc-950 p-2 text-sm"><option value="">Choose exact library entry</option>{games.map(g=><option key={g.id} value={g.id}>{g.title} · {g.platform || g.store} · #{g.id}</option>)}</select><button disabled={busy || !selected} onClick={()=>save(Number(selected))} className="rounded-lg bg-amber-200 px-3 text-sm font-bold text-black disabled:opacity-40">Link selected game</button><button disabled={busy} onClick={()=>save(null)} className="rounded-lg border border-zinc-700 px-3 text-sm disabled:opacity-40">Reject automatic match</button></div>{error && <p role="alert" className="mt-2 text-sm text-red-300">{error}</p>}</article>;
}
export default function AwardsReview() {
  const [entries,setEntries]=useState<Entry[]>([]);const [page,setPage]=useState(1);const [count,setCount]=useState(0);const [revision,setRevision]=useState(0);const [error,setError]=useState("");
  useEffect(()=>{const controller=new AbortController();fetch(`/api/admin/awards?page=${page}`,{signal:controller.signal}).then(async r=>{const data=await r.json();if(!r.ok)throw Error(data.error);setEntries(data.entries);setCount(data.count);setError("");}).catch(e=>{if(!controller.signal.aborted)setError(e.message);});return()=>controller.abort();},[page,revision]);
  return <><p role="status" className="mb-4 text-sm text-zinc-500">{count} unmatched or rejected entries</p>{error && <p role="alert" className="text-red-300">{error}</p>}<div className="space-y-3">{entries.map(e=><ReviewRow key={e.id} entry={e} onSaved={()=>setRevision(n=>n+1)}/>)}</div><div className="my-6 flex items-center justify-between"><button disabled={page===1} onClick={()=>setPage(n=>n-1)} className="disabled:opacity-30">Previous</button><span>Page {page}</span><button disabled={page*30>=count} onClick={()=>setPage(n=>n+1)} className="disabled:opacity-30">Next</button></div></>;
}
