begin;

-- Which episodes have been watched, independent of which are owned
-- (watch_owned_episodes records the files on the hard disk). The app keeps
-- watch_library_entries.episodes_watched equal to this table's row count.
create table if not exists public.watch_watched_episodes (
  id bigint generated by default as identity primary key,
  library_entry_id bigint not null
    references public.watch_library_entries(id)
    on delete cascade,
  episode_id bigint not null
    references public.watch_episodes(id)
    on delete cascade,
  watched_at timestamptz not null default now(),
  constraint watch_watched_episodes_library_entry_episode_key
    unique (library_entry_id, episode_id)
);

create index if not exists watch_watched_episodes_library_entry_id_idx
on public.watch_watched_episodes (library_entry_id);

create index if not exists watch_watched_episodes_episode_id_idx
on public.watch_watched_episodes (episode_id);

alter table public.watch_watched_episodes enable row level security;

commit;
