begin;

create table public.watch_import_items (
  id bigint generated by default as identity primary key,
  source_key text not null,
  local_title text not null,
  local_type text not null,
  local_file_count integer not null default 0,
  local_season_count integer not null default 0,
  local_episode_count integer not null default 0,
  local_summary jsonb not null default '{}'::jsonb,
  status text not null default 'pending',
  matched_media_id bigint,
  notes text,
  matched_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint watch_import_items_source_key_key
    unique (source_key),
  constraint watch_import_items_local_type_check
    check (local_type in ('series', 'movie', 'ova')),
  constraint watch_import_items_status_check
    check (status in ('pending', 'matched', 'skipped')),
  constraint watch_import_items_local_file_count_check
    check (local_file_count >= 0),
  constraint watch_import_items_local_season_count_check
    check (local_season_count >= 0),
  constraint watch_import_items_local_episode_count_check
    check (local_episode_count >= 0),
  constraint watch_import_items_matched_media_id_fkey
    foreign key (matched_media_id)
    references public.watch_media(id)
    on delete set null
);

create index watch_import_items_status_idx
on public.watch_import_items (status);

create index watch_import_items_matched_media_id_idx
on public.watch_import_items (matched_media_id);

create index watch_import_items_local_type_idx
on public.watch_import_items (local_type);

create index watch_import_items_lower_local_title_idx
on public.watch_import_items (lower(local_title));

create trigger set_watch_import_items_updated_at
before update on public.watch_import_items
for each row
execute function public.set_updated_at();

alter table public.watch_import_items enable row level security;

commit;
