begin;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create table public.watch_media (
  id bigint generated by default as identity primary key,
  title text not null,
  original_title text,
  alternative_titles text[] not null default '{}',
  slug text,
  media_type text not null,
  format text not null,
  tmdb_type text,
  tmdb_id integer,
  anilist_id integer,
  mal_id integer,
  overview text,
  poster_url text,
  backdrop_url text,
  release_date date,
  end_date date,
  airing_status text,
  tmdb_score numeric,
  anilist_score numeric,
  genres text[] not null default '{}',
  studios text[] not null default '{}',
  total_episodes integer,
  episode_duration integer,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint watch_media_media_type_check
    check (media_type in ('anime', 'tv', 'movie')),
  constraint watch_media_format_check
    check (format in ('series', 'movie', 'ova', 'ona', 'special')),
  constraint watch_media_tmdb_type_check
    check (tmdb_type is null or tmdb_type in ('tv', 'movie')),
  constraint watch_media_tmdb_type_id_check
    check (
      (tmdb_type is null and tmdb_id is null)
      or (tmdb_type is not null and tmdb_id is not null)
    ),
  constraint watch_media_tmdb_score_check
    check (tmdb_score is null or tmdb_score between 0 and 10),
  constraint watch_media_anilist_score_check
    check (anilist_score is null or anilist_score between 0 and 10),
  constraint watch_media_type_format_check
    check (
      (media_type = 'movie' and format = 'movie')
      or (media_type = 'tv' and format = 'series')
      or (
        media_type = 'anime'
        and format in ('series', 'movie', 'ova', 'ona', 'special')
      )
    ),
  constraint watch_media_total_episodes_check
    check (total_episodes is null or total_episodes >= 0),
  constraint watch_media_episode_duration_check
    check (episode_duration is null or episode_duration >= 0)
);

create table public.watch_seasons (
  id bigint generated by default as identity primary key,
  media_id bigint not null,
  season_number integer not null,
  title text,
  overview text,
  poster_url text,
  air_date date,
  episode_count integer,
  tmdb_season_id integer,
  anilist_id integer,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint watch_seasons_media_id_fkey
    foreign key (media_id)
    references public.watch_media(id)
    on delete cascade,
  constraint watch_seasons_season_number_check
    check (season_number >= 0),
  constraint watch_seasons_episode_count_check
    check (episode_count is null or episode_count >= 0),
  constraint watch_seasons_media_id_season_number_key
    unique (media_id, season_number)
);

create table public.watch_episodes (
  id bigint generated by default as identity primary key,
  season_id bigint not null,
  episode_number integer not null,
  tmdb_episode_id integer,
  title text,
  overview text,
  air_date date,
  airing_at timestamptz,
  still_url text,
  duration integer,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint watch_episodes_season_id_fkey
    foreign key (season_id)
    references public.watch_seasons(id)
    on delete cascade,
  constraint watch_episodes_episode_number_check
    check (episode_number >= 0),
  constraint watch_episodes_duration_check
    check (duration is null or duration >= 0),
  constraint watch_episodes_season_id_episode_number_key
    unique (season_id, episode_number)
);

create table public.watch_library_entries (
  id bigint generated by default as identity primary key,
  media_id bigint not null,
  watch_status text not null default 'Plan to Watch',
  my_score numeric,
  episodes_watched integer not null default 0,
  date_added date not null default current_date,
  date_started date,
  completion_last_watched date,
  rewatch_count integer not null default 0,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint watch_library_entries_media_id_fkey
    foreign key (media_id)
    references public.watch_media(id)
    on delete cascade,
  constraint watch_library_entries_watch_status_check
    check (
      watch_status in (
        'Plan to Watch',
        'Watching',
        'Completed',
        'On Hold',
        'Dropped',
        'Skipped',
        'Rewatching'
      )
    ),
  constraint watch_library_entries_my_score_check
    check (my_score is null or my_score between 0 and 10),
  constraint watch_library_entries_episodes_watched_check
    check (episodes_watched >= 0),
  constraint watch_library_entries_rewatch_count_check
    check (rewatch_count >= 0),
  constraint watch_library_entries_media_id_key
    unique (media_id)
);

create table public.watch_files (
  id bigint generated by default as identity primary key,
  media_id bigint not null,
  season_id bigint,
  episode_id bigint,
  file_kind text not null,
  file_name text not null,
  file_path text not null,
  file_size bigint,
  available_on_disk boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint watch_files_media_id_fkey
    foreign key (media_id)
    references public.watch_media(id)
    on delete cascade,
  constraint watch_files_season_id_fkey
    foreign key (season_id)
    references public.watch_seasons(id)
    on delete set null,
  constraint watch_files_episode_id_fkey
    foreign key (episode_id)
    references public.watch_episodes(id)
    on delete set null,
  constraint watch_files_file_kind_check
    check (file_kind in ('Episode', 'Movie', 'OVA', 'Special', 'Extra', 'NCOP', 'NCED')),
  constraint watch_files_file_size_check
    check (file_size is null or file_size >= 0),
  constraint watch_files_file_path_key
    unique (file_path)
);

create unique index watch_media_tmdb_type_tmdb_id_key
on public.watch_media (tmdb_type, tmdb_id)
where tmdb_id is not null;

create unique index watch_media_anilist_id_key
on public.watch_media (anilist_id)
where anilist_id is not null;

create unique index watch_media_mal_id_key
on public.watch_media (mal_id)
where mal_id is not null;

create unique index watch_media_slug_key
on public.watch_media (slug)
where slug is not null;

create index watch_media_lower_title_idx
on public.watch_media (lower(title));

create index watch_media_media_type_idx
on public.watch_media (media_type);

create index watch_media_format_idx
on public.watch_media (format);

create index watch_media_anilist_id_idx
on public.watch_media (anilist_id)
where anilist_id is not null;

create index watch_media_release_date_idx
on public.watch_media (release_date);

create index watch_seasons_media_id_idx
on public.watch_seasons (media_id);

create index watch_seasons_air_date_idx
on public.watch_seasons (air_date);

create index watch_episodes_season_id_idx
on public.watch_episodes (season_id);

create index watch_episodes_air_date_idx
on public.watch_episodes (air_date);

create index watch_episodes_airing_at_idx
on public.watch_episodes (airing_at);

create index watch_library_entries_watch_status_idx
on public.watch_library_entries (watch_status);

create index watch_library_entries_completion_last_watched_idx
on public.watch_library_entries (completion_last_watched);

create index watch_files_media_id_idx
on public.watch_files (media_id);

create index watch_files_season_id_idx
on public.watch_files (season_id)
where season_id is not null;

create index watch_files_episode_id_idx
on public.watch_files (episode_id)
where episode_id is not null;

create index watch_files_file_kind_idx
on public.watch_files (file_kind);

create index watch_files_available_on_disk_idx
on public.watch_files (available_on_disk);

create trigger set_watch_media_updated_at
before update on public.watch_media
for each row
execute function public.set_updated_at();

create trigger set_watch_seasons_updated_at
before update on public.watch_seasons
for each row
execute function public.set_updated_at();

create trigger set_watch_episodes_updated_at
before update on public.watch_episodes
for each row
execute function public.set_updated_at();

create trigger set_watch_library_entries_updated_at
before update on public.watch_library_entries
for each row
execute function public.set_updated_at();

create trigger set_watch_files_updated_at
before update on public.watch_files
for each row
execute function public.set_updated_at();

alter table public.watch_media enable row level security;
alter table public.watch_seasons enable row level security;
alter table public.watch_episodes enable row level security;
alter table public.watch_library_entries enable row level security;
alter table public.watch_files enable row level security;

commit;
