begin;

drop function if exists public.confirm_watch_import_match(bigint, jsonb, jsonb, jsonb, jsonb);
drop function if exists public.confirm_watch_import_match(bigint, jsonb, jsonb, jsonb);

create table if not exists public.watch_owned_episodes (
  id bigint generated by default as identity primary key,
  library_entry_id bigint not null
    references public.watch_library_entries(id)
    on delete cascade,
  episode_id bigint not null
    references public.watch_episodes(id)
    on delete cascade,
  created_at timestamptz not null default now(),
  constraint watch_owned_episodes_library_entry_episode_key
    unique (library_entry_id, episode_id)
);

create index if not exists watch_owned_episodes_library_entry_id_idx
on public.watch_owned_episodes (library_entry_id);

create index if not exists watch_owned_episodes_episode_id_idx
on public.watch_owned_episodes (episode_id);

alter table public.watch_owned_episodes enable row level security;

create or replace function public.confirm_watch_import_match(
  p_import_item_id bigint,
  p_media jsonb,
  p_seasons jsonb,
  p_source_links jsonb,
  p_owned_episodes jsonb
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  v_import public.watch_import_items%rowtype;
  v_media_id bigint;
  v_existing_slug_media_id bigint;
  v_slug text;
  v_slug_suffix text;
  v_season jsonb;
  v_episode jsonb;
  v_owned_episode jsonb;
  v_source_link jsonb;
  v_season_id bigint;
  v_episode_id bigint;
  v_library_entry_id bigint;
  v_conflict_media_id bigint;
begin
  select *
  into v_import
  from public.watch_import_items
  where id = p_import_item_id
  for update;

  if not found then
    raise exception 'IMPORT_ITEM_NOT_FOUND: watch_import_items id % does not exist', p_import_item_id;
  end if;

  if p_media is null or jsonb_typeof(p_media) <> 'object' then
    raise exception 'INVALID_MEDIA_PAYLOAD: p_media must be an object';
  end if;

  if p_source_links is null or jsonb_typeof(p_source_links) <> 'array' then
    raise exception 'INVALID_SOURCE_LINKS_PAYLOAD: p_source_links must be an array';
  end if;

  if p_seasons is null then
    p_seasons := '[]'::jsonb;
  end if;

  if jsonb_typeof(p_seasons) <> 'array' then
    raise exception 'INVALID_SEASONS_PAYLOAD: p_seasons must be an array';
  end if;

  if p_owned_episodes is null then
    p_owned_episodes := '[]'::jsonb;
  end if;

  if jsonb_typeof(p_owned_episodes) <> 'array' then
    raise exception 'INVALID_OWNED_EPISODES_PAYLOAD: p_owned_episodes must be an array';
  end if;

  if p_media ? 'tmdb_type' and p_media ? 'tmdb_id' then
    select id
    into v_media_id
    from public.watch_media
    where tmdb_type = p_media->>'tmdb_type'
      and tmdb_id = (p_media->>'tmdb_id')::integer
    limit 1;
  end if;

  if v_media_id is null and p_media ? 'anilist_id' then
    select id
    into v_media_id
    from public.watch_media
    where anilist_id = (p_media->>'anilist_id')::integer
    limit 1;
  end if;

  if v_media_id is null and p_media ? 'mal_id' then
    select id
    into v_media_id
    from public.watch_media
    where mal_id = (p_media->>'mal_id')::integer
    limit 1;
  end if;

  for v_source_link in
    select value from jsonb_array_elements(p_source_links)
  loop
    select media_id
    into v_conflict_media_id
    from public.watch_source_links
    where source = v_source_link->>'source'
      and coalesce(source_type, '') = coalesce(nullif(v_source_link->>'source_type', ''), '')
      and source_id = (v_source_link->>'source_id')::integer
    limit 1;

    if v_conflict_media_id is not null then
      if v_media_id is null then
        v_media_id := v_conflict_media_id;
      elsif v_media_id <> v_conflict_media_id then
        raise exception 'SOURCE_IDENTITY_CONFLICT: % % % is already linked to media %',
          v_source_link->>'source',
          coalesce(nullif(v_source_link->>'source_type', ''), 'null'),
          v_source_link->>'source_id',
          v_conflict_media_id;
      end if;
    end if;
  end loop;

  if v_import.status = 'matched'
     and v_import.matched_media_id is not null
     and (v_media_id is null or v_media_id <> v_import.matched_media_id) then
    raise exception 'IMPORT_ITEM_ALREADY_MATCHED: import item % is already matched to media %',
      p_import_item_id,
      v_import.matched_media_id;
  end if;

  v_slug := nullif(p_media->>'slug', '');

  if v_slug is not null then
    select id
    into v_existing_slug_media_id
    from public.watch_media
    where slug = v_slug
    limit 1;

    if v_existing_slug_media_id is not null
       and (v_media_id is null or v_existing_slug_media_id <> v_media_id) then
      v_slug_suffix := coalesce(
        'tmdb-' || nullif(p_media->>'tmdb_type', '') || '-' || nullif(p_media->>'tmdb_id', ''),
        'anilist-' || nullif(p_media->>'anilist_id', ''),
        'mal-' || nullif(p_media->>'mal_id', ''),
        'import-' || p_import_item_id::text
      );
      v_slug := v_slug || '-' || v_slug_suffix;
    end if;
  end if;

  if v_media_id is null then
    insert into public.watch_media (
      title,
      original_title,
      alternative_titles,
      slug,
      media_type,
      format,
      tmdb_type,
      tmdb_id,
      anilist_id,
      mal_id,
      overview,
      poster_url,
      backdrop_url,
      release_date,
      end_date,
      airing_status,
      tmdb_score,
      anilist_score,
      genres,
      studios,
      total_episodes,
      episode_duration
    )
    values (
      p_media->>'title',
      nullif(p_media->>'original_title', ''),
      coalesce(array(select jsonb_array_elements_text(coalesce(p_media->'alternative_titles', '[]'::jsonb))), '{}'),
      v_slug,
      p_media->>'media_type',
      p_media->>'format',
      nullif(p_media->>'tmdb_type', ''),
      nullif(p_media->>'tmdb_id', '')::integer,
      nullif(p_media->>'anilist_id', '')::integer,
      nullif(p_media->>'mal_id', '')::integer,
      nullif(p_media->>'overview', ''),
      nullif(p_media->>'poster_url', ''),
      nullif(p_media->>'backdrop_url', ''),
      nullif(p_media->>'release_date', '')::date,
      nullif(p_media->>'end_date', '')::date,
      nullif(p_media->>'airing_status', ''),
      nullif(p_media->>'tmdb_score', '')::numeric,
      nullif(p_media->>'anilist_score', '')::numeric,
      coalesce(array(select jsonb_array_elements_text(coalesce(p_media->'genres', '[]'::jsonb))), '{}'),
      coalesce(array(select jsonb_array_elements_text(coalesce(p_media->'studios', '[]'::jsonb))), '{}'),
      nullif(p_media->>'total_episodes', '')::integer,
      nullif(p_media->>'episode_duration', '')::integer
    )
    returning id into v_media_id;
  else
    update public.watch_media
    set
      original_title = coalesce(watch_media.original_title, nullif(p_media->>'original_title', '')),
      alternative_titles = case
        when cardinality(watch_media.alternative_titles) = 0
        then coalesce(array(select jsonb_array_elements_text(coalesce(p_media->'alternative_titles', '[]'::jsonb))), '{}')
        else watch_media.alternative_titles
      end,
      slug = coalesce(watch_media.slug, v_slug),
      tmdb_type = coalesce(watch_media.tmdb_type, nullif(p_media->>'tmdb_type', '')),
      tmdb_id = coalesce(watch_media.tmdb_id, nullif(p_media->>'tmdb_id', '')::integer),
      anilist_id = coalesce(watch_media.anilist_id, nullif(p_media->>'anilist_id', '')::integer),
      mal_id = coalesce(watch_media.mal_id, nullif(p_media->>'mal_id', '')::integer),
      overview = coalesce(watch_media.overview, nullif(p_media->>'overview', '')),
      poster_url = coalesce(watch_media.poster_url, nullif(p_media->>'poster_url', '')),
      backdrop_url = coalesce(watch_media.backdrop_url, nullif(p_media->>'backdrop_url', '')),
      release_date = coalesce(watch_media.release_date, nullif(p_media->>'release_date', '')::date),
      end_date = coalesce(watch_media.end_date, nullif(p_media->>'end_date', '')::date),
      airing_status = coalesce(watch_media.airing_status, nullif(p_media->>'airing_status', '')),
      tmdb_score = coalesce(watch_media.tmdb_score, nullif(p_media->>'tmdb_score', '')::numeric),
      anilist_score = coalesce(watch_media.anilist_score, nullif(p_media->>'anilist_score', '')::numeric),
      genres = case
        when cardinality(watch_media.genres) = 0
        then coalesce(array(select jsonb_array_elements_text(coalesce(p_media->'genres', '[]'::jsonb))), '{}')
        else watch_media.genres
      end,
      studios = case
        when cardinality(watch_media.studios) = 0
        then coalesce(array(select jsonb_array_elements_text(coalesce(p_media->'studios', '[]'::jsonb))), '{}')
        else watch_media.studios
      end,
      total_episodes = coalesce(watch_media.total_episodes, nullif(p_media->>'total_episodes', '')::integer),
      episode_duration = coalesce(watch_media.episode_duration, nullif(p_media->>'episode_duration', '')::integer)
    where id = v_media_id;
  end if;

  if v_import.status = 'matched'
     and v_import.matched_media_id is not null
     and v_import.matched_media_id <> v_media_id then
    raise exception 'IMPORT_ITEM_ALREADY_MATCHED: import item % is already matched to media %',
      p_import_item_id,
      v_import.matched_media_id;
  end if;

  insert into public.watch_library_entries (
    media_id,
    watch_status,
    episodes_watched,
    rewatch_count
  )
  values (
    v_media_id,
    'Plan to Watch',
    0,
    0
  )
  on conflict (media_id) do update
  set media_id = excluded.media_id
  returning id into v_library_entry_id;

  delete from public.watch_owned_episodes
  where library_entry_id = v_library_entry_id;

  for v_season in
    select value from jsonb_array_elements(p_seasons)
  loop
    insert into public.watch_seasons (
      media_id,
      season_number,
      title,
      overview,
      poster_url,
      air_date,
      episode_count,
      tmdb_season_id,
      anilist_id
    )
    values (
      v_media_id,
      (v_season->>'season_number')::integer,
      nullif(v_season->>'title', ''),
      nullif(v_season->>'overview', ''),
      nullif(v_season->>'poster_url', ''),
      nullif(v_season->>'air_date', '')::date,
      nullif(v_season->>'episode_count', '')::integer,
      nullif(v_season->>'tmdb_season_id', '')::integer,
      nullif(v_season->>'anilist_id', '')::integer
    )
    on conflict (media_id, season_number) do update
    set
      title = coalesce(watch_seasons.title, excluded.title),
      overview = coalesce(watch_seasons.overview, excluded.overview),
      poster_url = coalesce(watch_seasons.poster_url, excluded.poster_url),
      air_date = coalesce(watch_seasons.air_date, excluded.air_date),
      episode_count = coalesce(watch_seasons.episode_count, excluded.episode_count),
      tmdb_season_id = coalesce(watch_seasons.tmdb_season_id, excluded.tmdb_season_id),
      anilist_id = coalesce(watch_seasons.anilist_id, excluded.anilist_id)
    returning id into v_season_id;

    for v_episode in
      select value from jsonb_array_elements(coalesce(v_season->'episodes', '[]'::jsonb))
    loop
      insert into public.watch_episodes (
        season_id,
        episode_number,
        tmdb_episode_id,
        title,
        overview,
        air_date,
        still_url,
        duration
      )
      values (
        v_season_id,
        (v_episode->>'episode_number')::integer,
        nullif(v_episode->>'tmdb_episode_id', '')::integer,
        nullif(v_episode->>'title', ''),
        nullif(v_episode->>'overview', ''),
        nullif(v_episode->>'air_date', '')::date,
        nullif(v_episode->>'still_url', ''),
        nullif(v_episode->>'duration', '')::integer
      )
      on conflict (season_id, episode_number) do update
      set
        tmdb_episode_id = coalesce(watch_episodes.tmdb_episode_id, excluded.tmdb_episode_id),
        title = coalesce(watch_episodes.title, excluded.title),
        overview = coalesce(watch_episodes.overview, excluded.overview),
        air_date = coalesce(watch_episodes.air_date, excluded.air_date),
        still_url = coalesce(watch_episodes.still_url, excluded.still_url),
        duration = coalesce(watch_episodes.duration, excluded.duration)
      returning id into v_episode_id;
    end loop;
  end loop;

  for v_owned_episode in
    select value from jsonb_array_elements(p_owned_episodes)
  loop
    select watch_episodes.id
    into v_episode_id
    from public.watch_seasons
    join public.watch_episodes
      on watch_episodes.season_id = watch_seasons.id
    where watch_seasons.media_id = v_media_id
      and watch_seasons.season_number = (v_owned_episode->>'seasonNumber')::integer
      and watch_episodes.episode_number = (v_owned_episode->>'episodeNumber')::integer
    limit 1;

    if v_episode_id is null then
      raise exception 'INVALID_OWNED_EPISODE: season % episode % does not exist for media %',
        v_owned_episode->>'seasonNumber',
        v_owned_episode->>'episodeNumber',
        v_media_id;
    end if;

    insert into public.watch_owned_episodes (
      library_entry_id,
      episode_id
    )
    values (
      v_library_entry_id,
      v_episode_id
    )
    on conflict (library_entry_id, episode_id) do nothing;
  end loop;

  for v_source_link in
    select value from jsonb_array_elements(p_source_links)
  loop
    select media_id
    into v_conflict_media_id
    from public.watch_source_links
    where source = v_source_link->>'source'
      and coalesce(source_type, '') = coalesce(nullif(v_source_link->>'source_type', ''), '')
      and source_id = (v_source_link->>'source_id')::integer
    limit 1;

    if v_conflict_media_id is not null and v_conflict_media_id <> v_media_id then
      raise exception 'SOURCE_IDENTITY_CONFLICT: % % % is already linked to media %',
        v_source_link->>'source',
        coalesce(nullif(v_source_link->>'source_type', ''), 'null'),
        v_source_link->>'source_id',
        v_conflict_media_id;
    end if;

    insert into public.watch_source_links (
      media_id,
      source,
      source_id,
      source_type,
      relation_type,
      part_number,
      episode_count,
      episode_offset
    )
    values (
      v_media_id,
      v_source_link->>'source',
      (v_source_link->>'source_id')::integer,
      nullif(v_source_link->>'source_type', ''),
      coalesce(nullif(v_source_link->>'relation_type', ''), 'primary'),
      nullif(v_source_link->>'part_number', '')::integer,
      nullif(v_source_link->>'episode_count', '')::integer,
      coalesce(nullif(v_source_link->>'episode_offset', '')::integer, 0)
    )
    on conflict (source, (coalesce(source_type, '')), source_id) do nothing;
  end loop;

  update public.watch_import_items
  set
    status = 'matched',
    matched_media_id = v_media_id,
    matched_at = now()
  where id = p_import_item_id;

  return v_media_id;
end;
$$;

revoke all on function public.confirm_watch_import_match(bigint, jsonb, jsonb, jsonb, jsonb) from public;
revoke all on function public.confirm_watch_import_match(bigint, jsonb, jsonb, jsonb, jsonb) from anon;
revoke all on function public.confirm_watch_import_match(bigint, jsonb, jsonb, jsonb, jsonb) from authenticated;
grant execute on function public.confirm_watch_import_match(bigint, jsonb, jsonb, jsonb, jsonb) to service_role;

commit;
