begin;

create table public.watch_source_links (
  id bigint generated by default as identity primary key,
  media_id bigint not null,
  season_id bigint,
  source text not null,
  source_id integer not null,
  source_type text,
  relation_type text not null default 'primary',
  part_number integer,
  episode_count integer,
  episode_offset integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint watch_source_links_media_id_fkey
    foreign key (media_id)
    references public.watch_media(id)
    on delete cascade,
  constraint watch_source_links_season_id_fkey
    foreign key (season_id)
    references public.watch_seasons(id)
    on delete set null,
  constraint watch_source_links_source_check
    check (source in ('tmdb', 'anilist', 'mal')),
  constraint watch_source_links_source_type_check
    check (
      (
        source = 'tmdb'
        and source_type in ('tv', 'movie')
      )
      or (
        source in ('anilist', 'mal')
        and source_type is null
      )
    ),
  constraint watch_source_links_relation_type_check
    check (relation_type in ('primary', 'part', 'season', 'special', 'movie')),
  constraint watch_source_links_part_number_check
    check (part_number is null or part_number > 0),
  constraint watch_source_links_episode_count_check
    check (episode_count is null or episode_count >= 0),
  constraint watch_source_links_episode_offset_check
    check (episode_offset >= 0)
);

create unique index watch_source_links_source_identity_key
on public.watch_source_links (
  source,
  coalesce(source_type, ''),
  source_id
);

create unique index watch_source_links_media_source_identity_key
on public.watch_source_links (
  media_id,
  source,
  coalesce(source_type, ''),
  source_id
);

create index watch_source_links_media_id_idx
on public.watch_source_links (media_id);

create index watch_source_links_season_id_idx
on public.watch_source_links (season_id)
where season_id is not null;

create index watch_source_links_source_idx
on public.watch_source_links (source);

create index watch_source_links_media_id_source_idx
on public.watch_source_links (media_id, source);

create index watch_source_links_relation_type_idx
on public.watch_source_links (relation_type);

create or replace function public.validate_watch_source_link_season()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  if new.season_id is null then
    return new;
  end if;

  if not exists (
    select 1
    from public.watch_seasons
    where watch_seasons.id = new.season_id
      and watch_seasons.media_id = new.media_id
  ) then
    raise exception
      'watch_source_links season_id % does not belong to media_id %',
      new.season_id,
      new.media_id;
  end if;

  return new;
end;
$$;

create trigger validate_watch_source_link_season_trigger
before insert or update of media_id, season_id
on public.watch_source_links
for each row
execute function public.validate_watch_source_link_season();

create trigger set_watch_source_links_updated_at
before update on public.watch_source_links
for each row
execute function public.set_updated_at();

alter table public.watch_source_links enable row level security;

commit;
